<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:dwds="http://dupa.org/robmod.ecore" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmi:id="_FDPcQCwTEeKoaPJuKZ3ruQ" type="Robmod" name="${name}.robmod_diagram" measurementUnit="Pixel">
  <styles xmi:type="notation:DiagramStyle" xmi:id="_FDPcQSwTEeKoaPJuKZ3ruQ"/>
  <element xmi:type="dwds:Component" href="${name}.robmod#/"/>
</notation:Diagram>
